### ISSUE TITLE
Fatal Issue(/register) 

### ISSUE THREAD

**Issue by kangsLee** [maxtortime/EasyEditor#15]
/register 에서 회원가입시 Internal Server Error 발생

**Comment by maxtortime** [comment]
로컬에서는 되는데 서버에서는 안 되는 신묘한 현상이네요. 로그 확인해보겠습니다.

**Comment by maxtortime** [comment]
`2017-01-08T08:20:50.082930+00:00 app[web.1]: passlib.exc.MissingBackendError: no bcrypt backends available -- recommend you install one (e.g. 'pip install bcrypt')`

제가 저번에 requirments 정리하면서 bcrpyt를 빼먹은듯.. 곧 패치하겠습니다.
